repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7          # pin an exact Ruff release
    hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black]  # keeps style aligned with Ruff/Black